### ISSUE TITLE
Phonesaver allows unsupported files shared to it and it causes a crash.

### ISSUE THREAD

**Issue by kodeblacc** [ScreamingHawk/phone-saver#64]
On [Anexplorer](https://github.com/1hakr/AnExplorer/releases/download/v3.8/AnExplorer-googleFreeRelease-3.8.apk) Opening the audio category groups the music files in their respective albums and it has a share button meaning those albums can be shared. Sharing them directly to Phonesaver caused Phonesaver to crash.

``` FATAL EXCEPTION: main
Process: link.standen.michael.phonesaver, PID: 23495
java.lang.UnsupportedOperationException: Unsupported document videos_bucket:-296394803
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1179)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:998)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:718)
	at link.standen.michael.phonesaver.activity.SaverActivity.saveUri(SaverActivity.kt:338)
	at link.standen.michael.phonesaver.activity.SaverActivity.access$saveUri(SaverActivity.kt:31)
	at link.standen.michael.phonesaver.activity.SaverActivity$handleSingle$$inlined$let$lambda$1.invoke(SaverActivity.kt:272)
	at link.standen.michael.phonesaver.activity.SaverActivity$handleSingle$$inlined$let$lambda$1.invoke(SaverActivity.kt:31)
	at link.standen.michael.phonesaver.activity.SaverActivity.getFilename(SaverActivity.kt:506)
	at link.standen.michael.phonesaver.activity.SaverActivity.getFilename(SaverActivity.kt:399)
	at link.standen.michael.phonesaver.activity.SaverActivity.handleSingle(SaverActivity.kt:271)
	at link.standen.michael.phonesaver.activity.SaverActivity.useIntent(SaverActivity.kt:157)
	at link.standen.michael.phonesaver.activity.SaverActivity.useIntent$default(SaverActivity.kt:147)
	at link.standen.michael.phonesaver.activity.SaverActivity$loadList$$inlined$let$lambda$1$1.onItemClick(SaverActivity.kt:113)
	at android.widget.AdapterView.performItemClick(AdapterView.java:315)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1204)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3309)
	at android.widget.AbsListView$3.run(AbsListView.java:4378)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
```

**Comment by ScreamingHawk** [comment]
@kodeblacc In this case are you expecting that all files within the directory be saved via Phone Saver? 

Just want to confirm your intent
